[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dynamic_padding = false

opacity = 1.0
blur = false

decorations = "full"

[font]
normal.family = "RobotoMono Nerd Font"
normal.style = "Regular"
bold.style = "Bold"
italic.style = "Italic"
size = 14

[bell]
animation = "EaseOutExpo"
duration = 0
